# Generated by Django 4.0.5 on 2022-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0004_auto_20220719_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Ambitious',
        ),
        migrations.RemoveField(
            model_name='user',
            name='BasketballFan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='BeatlesFan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='DogLover',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EasyGoing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FilmBuff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gamer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Homebody',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MorningPerson',
        ),
        migrations.RemoveField(
            model_name='user',
            name='NatureLover',
        ),
        migrations.RemoveField(
            model_name='user',
            name='NightOwl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='StarWarsFan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ThrillSeeker',
        ),
        migrations.AddField(
            model_name='user',
            name='Location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Tags',
            field=models.JSONField(default={'Ambitious': 0, 'BasketballFan': 0, 'BeatlesFan': 0, 'DogLover': 0, 'EasyGoing': 0, 'FilmBuff': 0, 'Gamer': 0, 'Homebody': 0, 'MorningPerson': 0, 'NatureLover': 0, 'NightOwl': 0, 'StarWarsFan': 0, 'ThrillSeeker': 0}),
        ),
    ]
