# Generated by Django 4.0.5 on 2022-07-31 20:02

from django.db import migrations, models
import tag_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0005_remove_user_ambitious_remove_user_basketballfan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Tags',
            field=models.JSONField(default=tag_users.models.getDefaultTags),
        ),
    ]
