# Generated by Django 3.1.1 on 2022-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0007_user_matchcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cluster',
            field=models.IntegerField(default=-1),
        ),
    ]
