# Generated by Django 3.1.1 on 2022-08-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0008_user_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Cluster',
        ),
    ]
