# Generated by Django 4.0.5 on 2022-08-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0009_remove_user_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MatchedUser',
            field=models.CharField(default='', max_length=50),
        ),
    ]
