# Generated by Django 4.0.5 on 2022-08-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0010_user_matcheduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Matched',
            field=models.BooleanField(default=False),
        ),
    ]
