# Generated by Django 3.1.1 on 2022-08-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0011_user_matched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Location',
        ),
        migrations.AddField(
            model_name='user',
            name='InterestedLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='InterestedLong',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='LoggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
