# Generated by Django 3.1.1 on 2022-08-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0012_auto_20220813_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='LoggedIn',
            new_name='SignedIn',
        ),
    ]
