# Generated by Django 3.1.1 on 2022-08-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_users', '0013_auto_20220813_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MatchedUser',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='SignedIn',
            field=models.BooleanField(default=True),
        ),
    ]
